name: Daily Build

on:
  schedule:
    - cron: '0 21 * * *'
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Set Timezone
        run: sudo timedatectl set-timezone Asia/Shanghai

      - name: Generate Rule file
        run: go run main.go

      - name: Set env variables
        run: echo "GEN_MSG=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
        shell: bash

      - name: Commit & Push
        run: |
          git init
          git config --local user.name "${{ github.actor }}"
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          if [ -n "$(git status -s)" ]; then
            git add .
            git commit -m "${{ env.GEN_MSG }}"
            git push -f -u origin master
          fi
      
